-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "goose_db_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goose_db_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version_id" bigint NOT NULL,
	"is_applied" boolean NOT NULL,
	"tstamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_users" (
	"id" "ulid" PRIMARY KEY DEFAULT gen_ulid() NOT NULL,
	"username" varchar(64),
	"email" varchar(256) NOT NULL,
	"password_hash" text NOT NULL,
	"password_algo" varchar(64) DEFAULT 'bcrypt' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auth_users_username_key" UNIQUE("username"),
	CONSTRAINT "auth_users_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" "ulid" PRIMARY KEY DEFAULT gen_ulid() NOT NULL,
	"username" varchar(64) NOT NULL,
	"email" varchar(256) NOT NULL,
	"display_name" varchar(256),
	"avatar_url" varchar(256),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_key" UNIQUE("username"),
	CONSTRAINT "users_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "conversation_sessions" (
	"session_id" text PRIMARY KEY NOT NULL,
	"user_id" text,
	"tenant_id" text,
	"channel" text NOT NULL,
	"title" text,
	"deleted" boolean DEFAULT false NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"last_message_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"metadata" jsonb,
	CONSTRAINT "chk_conversation_sessions_channel" CHECK (channel = ANY (ARRAY['web-chat'::text, 'voice'::text, 'api'::text]))
);
--> statement-breakpoint
CREATE TABLE "conversation_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"msg_index" integer NOT NULL,
	"message" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "conversation_messages_msg_index_check" CHECK (msg_index >= 0)
);
--> statement-breakpoint
ALTER TABLE "conversation_messages" ADD CONSTRAINT "conversation_messages_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."conversation_sessions"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_conversation_sessions_last_message_at" ON "conversation_sessions" USING btree ("last_message_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_conversation_sessions_tenant_id" ON "conversation_sessions" USING btree ("tenant_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_conversation_sessions_user_id" ON "conversation_sessions" USING btree ("user_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_conversation_messages_created_at" ON "conversation_messages" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_conversation_messages_session_id_index" ON "conversation_messages" USING btree ("session_id" int4_ops,"msg_index" int4_ops);
*/